# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - db-test-conn

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: List Files in Working Directory
        run: ls -R

      - name: Check if composer.json exists
        run: |
          if [ -f ./laravel-sql-connection-test/composer.json ]; then
            echo "composer.json exists"
          else
            echo "composer.json does not exist"
            ls -R ./laravel-sql-connection-test
          fi
    
      - name: Run composer validate
        uses: php-actions/composer@v6
        with:
          args: validate --no-check-publish install 

      - name: Run composer install 
        uses: php-actions/composer@v6
        with:
          args: install --prefer-dist --no-progress
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: ./laravel-sql-connection-test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'db-test-conn'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9B257693AD8641A5B279FAD602C76A0E }}
          package: .
